### ISSUE TITLE
Index 1440px not passing markbot but in Browser looks the same as reference

### ISSUE THREAD

**Issue by dasi0075** [dasi0075/responsive-banner#1]
Hi @thomasjbradley
For when you see this.
My responsive banner is not passing Markbot, I am confused because when I open my browser I can see my banner content just as reference but Markbot keep showing as if wasn't showing.
Would appreciate some input on this.
Thank you
<img width="795" alt="Screen Shot 2020-01-12 at 5 11 13 PM" src="https://user-images.githubusercontent.com/43067752/72226406-d2ea7480-355e-11ea-958e-afd339e92790.png">

**Comment by thomasjbradley** [comment]
`position: relative` is on the wrong thing. It needs to be on a parent element of the thing that is `absolute`. So add a new `<div>` surrounding everything, that’s going to be `relative`

**Comment by dasi0075** [comment]
ok will try thank you @thomasjbradley
